// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAWCeEOZp-XRaLo4V4w3qNjWhxrcV5URY',
    appId: '1:1000605619922:web:6af261f474a6bdaf8abf0b',
    messagingSenderId: '1000605619922',
    projectId: 'family-flutter-workbook',
    authDomain: 'family-flutter-workbook.firebaseapp.com',
    storageBucket: 'family-flutter-workbook.firebasestorage.app',
    measurementId: 'G-NHVRXLPSPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6gk8rYIGsQ_KoFwrO4D46nHjavUkXhaA',
    appId: '1:1000605619922:android:3cc147b9221252ab8abf0b',
    messagingSenderId: '1000605619922',
    projectId: 'family-flutter-workbook',
    storageBucket: 'family-flutter-workbook.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAuaW4N-t1_8U6W2y3OcBSobuvLbqJu28',
    appId: '1:1000605619922:ios:c792630695fb73a08abf0b',
    messagingSenderId: '1000605619922',
    projectId: 'family-flutter-workbook',
    storageBucket: 'family-flutter-workbook.firebasestorage.app',
    iosClientId:
        '1000605619922-3mibvofs66ph2boh5srb4d8fensm8r0o.apps.googleusercontent.com',
    iosBundleId: 'com.example.familyWorkbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAuaW4N-t1_8U6W2y3OcBSobuvLbqJu28',
    appId: '1:1000605619922:ios:c792630695fb73a08abf0b',
    messagingSenderId: '1000605619922',
    projectId: 'family-flutter-workbook',
    storageBucket: 'family-flutter-workbook.firebasestorage.app',
    iosClientId:
        '1000605619922-3mibvofs66ph2boh5srb4d8fensm8r0o.apps.googleusercontent.com',
    iosBundleId: 'com.example.familyWorkbook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAWCeEOZp-XRaLo4V4w3qNjWhxrcV5URY',
    appId: '1:1000605619922:web:9a594e37e7ea68068abf0b',
    messagingSenderId: '1000605619922',
    projectId: 'family-flutter-workbook',
    authDomain: 'family-flutter-workbook.firebaseapp.com',
    storageBucket: 'family-flutter-workbook.firebasestorage.app',
    measurementId: 'G-0FRZM1MJFD',
  );
}
